export const data = [
  {
    title: "Bitcoin (BTC)",
    price: "$31,812.80",
    tvl: "$60,000",
    profit: "+10%",
    loss: "",
    pair: ["Solana (SOL)", "Ethereum (ETH)", "Binance USD (BUSD)"],
    color: "rgba(234, 179, 0, 0.6)",
  },
  {
    title: "Solana (SOL)",
    price: "$32.83",
    tvl: "$60,000",
    profit: "",
    loss: "-12.32%",
    pair: ["Bitcoin (BTC)", "Ethereum (ETH)", "Binance USD (BUSD)"],
    color: "#DC1FFF",
  },
  {
    title: "Ethereum (ETH)",
    price: "$1,466.45",
    tvl: "$60,000",
    profit: "",
    loss: "-11.93%",
    pair: ["Solana (SOL)", "Bitcoin (BTC)", "Binance USD (BUSD)"],
    color: "#EDF0F4",
  },
  {
    title: "Binance USD (BUSD)",
    price: "$1.00",
    tvl: "$60,000",
    profit: "+0.26%",
    loss: "",
    pair: ["Solana (SOL)", "Ethereum (ETH)", "Binance USD (BUSD)"],
    color: "#EAB300",
  },
  {
    title: "Shiba Inu (SHIB)",
    price: "$0.00000001948",
    tvl: "$60,000",
    profit: "",
    loss: "-8.1%",
    pair: ["Solana (SOL)", "Ethereum (ETH)", "Binance USD (BUSD)"],
    color: "#E42D04",
  },
];
