export const data = [
  {
    title: "Bitcoin (BTC)",
    price: "$31,812.80",
    tvl: "$60,000",
    profit: "+10%",
    loss: "",
    pair: ["Solana", "Ethereum", "Binance"],
    color: "rgba(234, 179, 0, 0.6)",
    img: "Bitcoin",
  },
  {
    title: "Solana (SOL)",
    price: "$32.83",
    tvl: "$60,000",
    profit: "",
    loss: "-12.32%",
    pair: ["Bitcoin", "Ethereum", "Binance"],
    color: "#DC1FFF",
    img: "Solana",
  },
  {
    title: "Ethereum (ETH)",
    price: "$1,466.45",
    tvl: "$60,000",
    profit: "",
    loss: "-11.93%",
    pair: ["Solana", "Bitcoin", "Binance"],
    color: "#EDF0F4",
    img: "Ethereum",
  },
  {
    title: "Binance USD (BUSD)",
    price: "$1.00",
    tvl: "$60,000",
    profit: "+0.26%",
    loss: "",
    pair: ["Solana", "Ethereum", "Binance"],
    color: "#EAB300",
    img: "Binance",
  },
  {
    title: "Shiba Inu (SHIB)",
    price: "$0.00000001948",
    tvl: "$60,000",
    profit: "",
    loss: "-8.1%",
    pair: ["Solana", "Ethereum", "Binance"],
    color: "#E42D04",
    img: "Shiba",
  },
];
